package com.betman.event.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Digits;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.math.BigDecimal;
import java.time.Instant;

/**
 * Manual event creation (admin). Odds are optional: when any of them is missing, all three are
 * generated by the OddsCalculator.
 */
public record CreateEventRequest(
		@NotBlank(message = "informe o time da casa")
		@Size(max = 60, message = "use no máximo 60 caracteres")
		String homeTeam,

		@NotBlank(message = "informe o time visitante")
		@Size(max = 60, message = "use no máximo 60 caracteres")
		String awayTeam,

		@NotNull(message = "informe o horário de início")
		Instant startsAt,

		@DecimalMin(value = "1.01", message = "a odd mínima é 1.01")
		@Digits(integer = 4, fraction = 2, message = "use no máximo 2 casas decimais")
		BigDecimal oddHome,

		@DecimalMin(value = "1.01", message = "a odd mínima é 1.01")
		@Digits(integer = 4, fraction = 2, message = "use no máximo 2 casas decimais")
		BigDecimal oddDraw,

		@DecimalMin(value = "1.01", message = "a odd mínima é 1.01")
		@Digits(integer = 4, fraction = 2, message = "use no máximo 2 casas decimais")
		BigDecimal oddAway) {

	public boolean hasAllOdds() {
		return oddHome != null && oddDraw != null && oddAway != null;
	}
}
